routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/profile', ProfileController::class);
    Route::resource('/projects', ProjectController::class);
    Route::resource('/skills', SkillController::class);
    Route::resource('/contacts', ContactController::class);
    Route::resource('/tags', TagController::class);
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/Api/ProjectController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ProjectResource;
use App\Models\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function index()
    {
        $projects = Project::with('tags')->get();

        return response()->json([
            'message' => 'This is all your Project',
            'data' => ProjectResource::collection($projects)
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProjectController extends Controller
{
    public function index()
    {
        $projects = Project::get();

        return view('project.index', compact('projects'));
    }

    public function create()
    {
        $tags = Tag::get();
        $project = new Project();

        return view('project.create', compact('tags', 'project'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'tags' => 'required',
            'thumbnail' => 'required|mimes:png, jpg, jpeg, svg, gif',
        ]);

        try {
            $thumbnail = $request->file('thumbnail');
            $thumbnailUrl = $thumbnail->storeAs('projects', Str::slug($request->name) . '.' . $thumbnail->extension());

            $project = Project::create([
                'name' => $request->name,
                'description' => $request->description,
                'link' => $request->link,
                'thumbnail' => $thumbnailUrl,
            ]);

            $project->tags()->attach($request->tags);

            return redirect()->route('projects.index')->with('success', 'Your project was created');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Project $project)
    {
        //
    }

    public function edit(Project $project)
    {

        $tags = Tag::get();

        return view('project.edit', compact('tags', 'project'));
    }

    public function update(Request $request, Project $project)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'tags' => 'required',
            'thumbnail' => 'mimes:png, jpg, jpeg, svg, gif',
        ]);

        try {
            if ($request->file('thumbnail')) {
                Storage::delete($project->thumbnail);
                $thumbnail = $request->file('thumbnail');
                $thumbnailUrl = $thumbnail->storeAs('projects', Str::slug($request->name) . '.' . $thumbnail->extension());
            } else {
                $thumbnailUrl = $project->thumbnail;
            }

            $project->update([
                'name' => $request->name,
                'description' => $request->description,
                'link' => $request->link,
                'thumbnail' => $thumbnailUrl,
            ]);

            $project->tags()->sync($request->tags);

            return redirect()->route('projects.index')->with('success', 'Your project was updated');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Project $project)
    {
        try {
            Storage::delete($project->thumbnail);
            $project->tags()->detach();
            $project->delete();

            return redirect()->route('projects.index')->with('success', 'Your project was deleted');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/project/create.blade.php
@extends('layouts.app', ['title' => 'Add Project'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Add Project</div>
            </div>

            <div class="card-body">
                <form action="{{ route('projects.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('project.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/project/edit.blade.php
@extends('layouts.app', ['title' => 'Edit Project'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Edit Project</div>
            </div>

            <div class="card-body">
                <form action="{{ route('projects.update', $project->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    @include('project.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/project/form.blade.php
<div class="form-group">
    <label for="name">Project Name</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ $project->name ?? old('name') }}">

    @error('name')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" id="description" rows="3" class="form-control">{{ $project->description ?? old('description') }}</textarea>

    @error('description')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="tags">Tags</label>
    <select name="tags[]" id="tags" class="form-control choices multiple-remove" multiple>
        @foreach($tags as $tag)
        <option value="{{ $tag->id }}">{{ $tag->name }}</option>
        @endforeach
        @if($project->id)
        @foreach($project->tags as $tag)
        <option selected value="{{ $tag->id }}">{{ $tag->name }}</option>
        @endforeach
        @endif
    </select>

    @error('tags')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="thumbnail">Thumbnail</label>
    <input type="file" name="thumbnail" id="thumbnail" class="form-control">

    @error('thumbnail')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="link">Link</label>
    <input type="text" name="link" id="link" class="form-control" value="{{ $project->link ?? old('link') }}">

    @error('link')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary">Save</button>
</div>

resources/views/project/index.blade.php
@extends('layouts.app', ['title' => 'Projects'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h2 class="card-title">Projects</h2>
                <a href="{{ route('projects.create') }}" class="btn btn-primary">Add Project</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Tags</th>
                                <th>Thumbnail</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($projects as $project)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td><a target="_blank" href="https://{{ $project->link }}">{{ $project->name }}</a></td>
                                <td>{{ $project->description }}</td>
                                <td>
                                    @foreach($project->tags as $tag)
                                    <span class="badge bg-secondary">{{ $tag->name }}</span>
                                    @endforeach
                                </td>
                                <td><img src="{{ asset('storage/' . $project->thumbnail) }}" alt="" width="100px"></td>
                                <td>
                                    <a href="{{ route('projects.edit', $project->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop