routes/web.php
<?php

use App\Http\Controllers\ContactController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/profile', ProfileController::class);
    Route::resource('/projects', ProjectController::class);
    Route::resource('/skills', SkillController::class);
    Route::resource('/contacts', ContactController::class);
    Route::resource('/tags', TagController::class);
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/Api/SkillController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\SkillResource;
use App\Models\Skill;
use Illuminate\Http\Request;

class SkillController extends Controller
{
    public function index()
    {
        $skills = Skill::get();

        return response()->json([
            'message' => 'This is all your Skill',
            'data' => SkillResource::collection($skills)
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function show(Skill $skill)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Skill $skill)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function destroy(Skill $skill)
    {
        //
    }
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skill;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SkillController extends Controller
{
    public function index()
    {
        $skills = Skill::get();

        return view('skill.index', compact('skills'));
    }

    public function create()
    {
        $skill = new Skill();

        return view('skill.create', compact('skill'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'experience' => 'required',
            'logo' => 'required',
            'logo.*' => 'mimes:jpg, jpeg, png, svg, gif',
        ]);

        try {
            $logo = $request->file('logo');
            $logoUrl = $logo->storeAs('skill', Str::slug($request->name) . '.' . $logo->extension());

            Skill::create([
                'name' => $request->name,
                'experience' => $request->experience,
                'logo' => $logoUrl,
            ]);

            return redirect()->route('skills.index')->with('success', 'Your skill was created');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Skill $skill)
    {
        //
    }

    public function edit(Skill $skill)
    {
        return view('skill.edit', compact('skill'));
    }

    public function update(Request $request, Skill $skill)
    {
        $request->validate([
            'name' => 'required',
            'experience' => 'required',
            'logo' => 'required',
            'logo.*' => 'mimes:jpg, jpeg, png, svg, gif',
        ]);

        try {
            if ($request->file('logo')) {
                Storage::delete($skill->logo);
                $logo = $request->file('logo');
                $logoUrl = $logo->storeAs('skill', Str::slug($request->name) . '.' . $logo->extension());
            } else {
                $logoUrl = $skill->logo;
            }

            $skill->update([
                'name' => $request->name,
                'experience' => $request->experience,
                'logo' => $logoUrl,
            ]);

            return redirect()->route('skills.index')->with('success', 'Your skill was updated');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Skill $skill)
    {
        try {
            Storage::delete($skill->logo);
            $skill->delete();

            return redirect()->route('skills.index')->with('success', 'Your skill was deleted');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/skill/create.blade.php
@extends('layouts.app', ['title' => 'Add Skill'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Add Skill</div>
            </div>

            <div class="card-body">
                <form action="{{ route('skills.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('skill.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/skill/edit.blade.php
@extends('layouts.app', ['title' => 'Edit Skill'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Edit Skill</div>
            </div>

            <div class="card-body">
                <form action="{{ route('skills.update', $skill->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    @include('skill.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/skill/form.blade.php
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" class="form-control" value="{{ $skill->name ?? old('name') }}">

    @error('name')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="experience">Experience</label>
    <input type="text" name="experience" id="experience" class="form-control" value="{{ $skill->experience ?? old('experience') }}">

    @error('experience')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="logo">Logo</label>
    <input type="file" name="logo" id="logo" class="form-control">

    @error('logo')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>


<div class="form-group">
    <button type="submit" class="btn btn-primary">Save</button>
</div>

resources/views/skill/index.blade.php
@extends('layouts.app', ['title' => 'Skills'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h2 class="card-title">Skills</h2>
                <a href="{{ route('skills.create') }}" class="btn btn-primary">Add Skill</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Logo</th>
                                <th>Name</th>
                                <th>Experience</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($skills as $skill)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td><img src="{{ asset('storage/' . $skill->logo) }}" alt="" width="70px"></td>
                                <td>{{ $skill->name }}</td>
                                <td>{{ $skill->experience }}</td>
                                <td>
                                    <a href="{{ route('skills.edit', $skill->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop